[project]
name = "urssi-pixi-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
example = "python analysis.py"

[dependencies]
python = "3.12.*"
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
