[project]
name = "urssi-pixi-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
